#-----------------------------------------------------------------------
#makefile commands
#-----------------------------------------------------------------------
include $(AUGEANSTABLES_CONFIG)/makefile_header.mk

#test_mpi_process
test_mpi_process.o:	$(mpi_dir)/mpi_process_class.o

test_mpi_process:	mpi_process_class.o


#test_mpi_tag
test_mpi_tag.o:		$(mpi_dir)/mpi_tag_module.o
test_mpi_tag:		mpi_tag_module.o