#-----------------------------------------------------------------------
#makefile commands
#-----------------------------------------------------------------------
include $(AUGEANSTABLES_CONFIG)/makefile_header.mk

#test_mpi_process
test_mpi_process.o:	$(mpi_dir)/mpi_process_class.o

test_mpi_process:	mpi_process_class.o